from py_db import db

#Creates MySQL tables for the mlb_prospects database

#This is an initialization script, and only needs to be run once, prior to running every other script


db = db('mlb_prospects')

q = """-- Create syntax for TABLE '_draft_list'
CREATE TABLE `_draft_list` (
  `DraftRank` bigint(21) DEFAULT NULL,
  `YearRank` bigint(21) DEFAULT NULL,
  `superAdjFV_rnk` bigint(21) DEFAULT NULL,
  `adjFV_rnk` bigint(21) DEFAULT NULL,
  `avgFV_rnk` bigint(21) DEFAULT NULL,
  `ofpFV_rnk` bigint(21) DEFAULT NULL,
  `superAdj_FV` varchar(63) DEFAULT NULL,
  `adj_FV` varchar(63) DEFAULT NULL,
  `avg_FV` varchar(75) DEFAULT NULL,
  `ofp_FV` varchar(63) DEFAULT NULL,
  `*BIO*` varchar(1) NOT NULL DEFAULT '',
  `fnames` varchar(129) DEFAULT NULL,
  `lnames` varchar(129) DEFAULT NULL,
  `age` varchar(51) DEFAULT NULL,
  `position` varchar(16) DEFAULT NULL,
  `bats` varchar(8) DEFAULT NULL,
  `throws` varchar(8) DEFAULT NULL,
  `height` varchar(11) DEFAULT NULL,
  `weight` varchar(11) DEFAULT NULL,
  `p_type` varchar(12) NOT NULL DEFAULT '',
  `FV_pts` bigint(20) NOT NULL DEFAULT '0',
  `FV_weight` decimal(16,0) NOT NULL DEFAULT '0',
  `*IDs*` varchar(1) NOT NULL DEFAULT '',
  `year` int(11) NOT NULL DEFAULT '0',
  `prospect_id` int(11) unsigned NOT NULL DEFAULT '0',
  `mlb_id` int(11) NOT NULL DEFAULT '0',
  `mlb_draft_id` varchar(64) DEFAULT NULL,
  `fg_major_id` int(11) DEFAULT NULL,
  `fg_minor_id` varchar(64) DEFAULT NULL,
  `*FG*` varchar(1) NOT NULL DEFAULT '',
  `FGOvrRnk` bigint(20) DEFAULT NULL,
  `FGSchool` varchar(64) DEFAULT NULL,
  `FG_Athleticism` bigint(20) DEFAULT NULL,
  `FG_Performer` bigint(20) DEFAULT NULL,
  `FG_Risk` bigint(20) DEFAULT NULL,
  `FG_Variance` varchar(16) DEFAULT NULL,
  `FG_ETA` bigint(20) DEFAULT NULL,
  `FG_FV` bigint(20) DEFAULT NULL,
  `FG_Video` text,
  `FG_ShortBlurb` text,
  `FG_Blurb` text,
  `*mlb*` varchar(1) NOT NULL DEFAULT '',
  `MLB_School` varchar(64) DEFAULT NULL,
  `MLB_Team` varchar(32) DEFAULT NULL,
  `MLB_Drafted` varchar(32) DEFAULT NULL,
  `MLB_Signed` varchar(32) DEFAULT NULL,
  `MLB_ETA` bigint(20) DEFAULT NULL,
  `MLB_FV` bigint(20) DEFAULT NULL,
  `MLB_Blurb` text,
  `*mi*` varchar(1) NOT NULL DEFAULT '',
  `mi_team` varchar(32) DEFAULT NULL,
  `mi_teamRank` int(11) DEFAULT NULL,
  `mi_grade` varchar(16) DEFAULT NULL,
  `mi_eta` varchar(64) DEFAULT NULL,
  `mi_FV` int(11) DEFAULT NULL,
  `*FG_PRO*` varchar(1) NOT NULL DEFAULT '',
  `FG_Team` varchar(32) DEFAULT NULL,
  `FG_Level` varchar(8) DEFAULT NULL,
  `FG_OrgRank` int(11) DEFAULT NULL,
  `FG_Signed` varchar(64) DEFAULT NULL,
  `*FG_DRAFT*` varchar(1) NOT NULL DEFAULT '',
  `FG_DraftRank` int(11) DEFAULT NULL,
  `FG_DraftPick` int(11) DEFAULT NULL,
  `FG_DraftTeam` varchar(32) DEFAULT NULL,
  `*MLB_PRO*` varchar(1) NOT NULL DEFAULT '',
  `MLB_OrgRank` int(11) DEFAULT NULL,
  `MLB_OvrRank` int(11) DEFAULT NULL,
  `*MLB_DRAFT*` varchar(1) NOT NULL DEFAULT '',
  `MLB_Grade` varchar(64) DEFAULT NULL,
  `MLB_Commit` varchar(64) DEFAULT NULL,
  `*OFP*` varchar(1) NOT NULL DEFAULT '',
  `FG_Hitters_pOFP` varchar(63) DEFAULT NULL,
  `FG_Hitters_fOFP` varchar(63) DEFAULT NULL,
  `MLB_Hitters_OFP` varchar(63) DEFAULT NULL,
  `FG_Pitchers_pOFP` varchar(67) DEFAULT NULL,
  `FG_Pitchers_fOFP` varchar(67) DEFAULT NULL,
  `MLB_Pitchers_OFP` varchar(70) DEFAULT NULL,
  `*BONUS_OFP*` varchar(1) NOT NULL DEFAULT '',
  `MaxVelo_Bonus` decimal(15,4) DEFAULT NULL,
  `FastballRPM_Bonus` decimal(15,4) DEFAULT NULL,
  `BreakingRPM_Bonus` decimal(15,4) DEFAULT NULL,
  `*FG_HIT*` varchar(1) NOT NULL DEFAULT '',
  `Hit_present` int(11) DEFAULT NULL,
  `GamePower_present` int(11) DEFAULT NULL,
  `RawPower_present` int(11) DEFAULT NULL,
  `Speed_present` int(11) DEFAULT NULL,
  `Field_present` int(11) DEFAULT NULL,
  `Throws_present` int(11) DEFAULT NULL,
  `Hit_future` int(11) DEFAULT NULL,
  `GamePower_future` int(11) DEFAULT NULL,
  `RawPower_future` int(11) DEFAULT NULL,
  `Speed_future` int(11) DEFAULT NULL,
  `Field_future` int(11) DEFAULT NULL,
  `Throws_future` int(11) DEFAULT NULL,
  `*FG_PITCH*` varchar(1) NOT NULL DEFAULT '',
  `TJ_Date` date DEFAULT NULL,
  `Fastball_RPM` int(11) DEFAULT NULL,
  `Breaking_RPM` int(11) DEFAULT NULL,
  `Command_present` int(11) DEFAULT NULL,
  `Fastball_present` int(11) DEFAULT NULL,
  `Changeup_present` int(11) DEFAULT NULL,
  `Curveball_present` int(11) DEFAULT NULL,
  `Slider_present` int(11) DEFAULT NULL,
  `Cutter_present` int(11) DEFAULT NULL,
  `Splitter_present` int(11) DEFAULT NULL,
  `Command_future` int(11) DEFAULT NULL,
  `Fastball_future` int(11) DEFAULT NULL,
  `Changeup_future` int(11) DEFAULT NULL,
  `Curveball_future` int(11) DEFAULT NULL,
  `Slider_future` int(11) DEFAULT NULL,
  `Cutter_future` int(11) DEFAULT NULL,
  `Splitter_future` int(11) DEFAULT NULL,
  `*MLB_HIT*` varchar(1) NOT NULL DEFAULT '',
  `hit` int(11) DEFAULT NULL,
  `power` int(11) DEFAULT NULL,
  `run` int(11) DEFAULT NULL,
  `arm` int(11) DEFAULT NULL,
  `field` int(11) DEFAULT NULL,
  `*MLB_PITCH*` varchar(1) NOT NULL DEFAULT '',
  `fastball` int(11) DEFAULT NULL,
  `change` int(11) DEFAULT NULL,
  `curve` int(11) DEFAULT NULL,
  `slider` int(11) DEFAULT NULL,
  `cutter` int(11) DEFAULT NULL,
  `splitter` int(11) DEFAULT NULL,
  `other` int(11) DEFAULT NULL,
  `control` int(11) DEFAULT NULL,
  `NSBL_Team` varchar(50) DEFAULT '',
  `NSBL_Salary` decimal(32,3),
  `NSBL_Year` varchar(50) DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Create syntax for TABLE '_master_current'
CREATE TABLE `_master_current` (
  `YearRank` bigint(21) DEFAULT NULL,
  `superAdjFV_rnk` bigint(21) DEFAULT NULL,
  `adjFV_rnk` bigint(21) DEFAULT NULL,
  `avgFV_rnk` bigint(21) DEFAULT NULL,
  `ofpFV_rnk` bigint(21) DEFAULT NULL,
  `superAdj_FV` varchar(63) DEFAULT NULL,
  `adj_FV` varchar(63) DEFAULT NULL,
  `avg_FV` varchar(75) DEFAULT NULL,
  `ofp_FV` varchar(63) DEFAULT NULL,
  `*BIO*` varchar(1) NOT NULL DEFAULT '',
  `fnames` varchar(129) DEFAULT NULL,
  `lnames` varchar(129) DEFAULT NULL,
  `age` varchar(51) DEFAULT NULL,
  `position` varchar(16) DEFAULT NULL,
  `bats` varchar(8) DEFAULT NULL,
  `throws` varchar(8) DEFAULT NULL,
  `height` varchar(11) DEFAULT NULL,
  `weight` varchar(11) DEFAULT NULL,
  `p_type` varchar(12) NOT NULL DEFAULT '',
  `FV_pts` bigint(20) NOT NULL DEFAULT '0',
  `FV_weight` decimal(16,0) NOT NULL DEFAULT '0',
  `*IDs*` varchar(1) NOT NULL DEFAULT '',
  `year` int(11) NOT NULL DEFAULT '0',
  `prospect_id` int(11) unsigned NOT NULL DEFAULT '0',
  `mlb_id` int(11) NOT NULL DEFAULT '0',
  `mlb_draft_id` varchar(64) DEFAULT NULL,
  `fg_major_id` int(11) DEFAULT NULL,
  `fg_minor_id` varchar(64) DEFAULT NULL,
  `*FG*` varchar(1) NOT NULL DEFAULT '',
  `FGOvrRnk` bigint(20) DEFAULT NULL,
  `FGSchool` varchar(64) DEFAULT NULL,
  `FG_Athleticism` bigint(20) DEFAULT NULL,
  `FG_Performer` bigint(20) DEFAULT NULL,
  `FG_Risk` bigint(20) DEFAULT NULL,
  `FG_Variance` varchar(16) DEFAULT NULL,
  `FG_ETA` bigint(20) DEFAULT NULL,
  `FG_FV` bigint(20) DEFAULT NULL,
  `FG_Video` text,
  `FG_ShortBlurb` text,
  `FG_Blurb` text,
  `*mlb*` varchar(1) NOT NULL DEFAULT '',
  `MLB_School` varchar(64) DEFAULT NULL,
  `MLB_Team` varchar(32) DEFAULT NULL,
  `MLB_Drafted` varchar(32) DEFAULT NULL,
  `MLB_Signed` varchar(32) DEFAULT NULL,
  `MLB_ETA` bigint(20) DEFAULT NULL,
  `MLB_FV` bigint(20) DEFAULT NULL,
  `MLB_Blurb` text,
  `*mi*` varchar(1) NOT NULL DEFAULT '',
  `mi_team` varchar(32) DEFAULT NULL,
  `mi_teamRank` int(11) DEFAULT NULL,
  `mi_grade` varchar(16) DEFAULT NULL,
  `mi_eta` varchar(64) DEFAULT NULL,
  `mi_FV` int(11) DEFAULT NULL,
  `*FG_PRO*` varchar(1) NOT NULL DEFAULT '',
  `FG_Team` varchar(32) DEFAULT NULL,
  `FG_Level` varchar(8) DEFAULT NULL,
  `FG_OrgRank` int(11) DEFAULT NULL,
  `FG_Signed` varchar(64) DEFAULT NULL,
  `*FG_DRAFT*` varchar(1) NOT NULL DEFAULT '',
  `FG_DraftRank` int(11) DEFAULT NULL,
  `FG_DraftPick` int(11) DEFAULT NULL,
  `FG_DraftTeam` varchar(32) DEFAULT NULL,
  `*MLB_PRO*` varchar(1) NOT NULL DEFAULT '',
  `MLB_OrgRank` int(11) DEFAULT NULL,
  `MLB_OvrRank` int(11) DEFAULT NULL,
  `*MLB_DRAFT*` varchar(1) NOT NULL DEFAULT '',
  `MLB_Grade` varchar(64) DEFAULT NULL,
  `MLB_Commit` varchar(64) DEFAULT NULL,
  `*OFP*` varchar(1) NOT NULL DEFAULT '',
  `FG_Hitters_pOFP` varchar(63) DEFAULT NULL,
  `FG_Hitters_fOFP` varchar(63) DEFAULT NULL,
  `MLB_Hitters_OFP` varchar(63) DEFAULT NULL,
  `FG_Pitchers_pOFP` varchar(67) DEFAULT NULL,
  `FG_Pitchers_fOFP` varchar(67) DEFAULT NULL,
  `MLB_Pitchers_OFP` varchar(70) DEFAULT NULL,
  `*BONUS_OFP*` varchar(1) NOT NULL DEFAULT '',
  `MaxVelo_Bonus` decimal(15,4) DEFAULT NULL,
  `FastballRPM_Bonus` decimal(15,4) DEFAULT NULL,
  `BreakingRPM_Bonus` decimal(15,4) DEFAULT NULL,
  `*FG_HIT*` varchar(1) NOT NULL DEFAULT '',
  `Hit_present` int(11) DEFAULT NULL,
  `GamePower_present` int(11) DEFAULT NULL,
  `RawPower_present` int(11) DEFAULT NULL,
  `Speed_present` int(11) DEFAULT NULL,
  `Field_present` int(11) DEFAULT NULL,
  `Throws_present` int(11) DEFAULT NULL,
  `Hit_future` int(11) DEFAULT NULL,
  `GamePower_future` int(11) DEFAULT NULL,
  `RawPower_future` int(11) DEFAULT NULL,
  `Speed_future` int(11) DEFAULT NULL,
  `Field_future` int(11) DEFAULT NULL,
  `Throws_future` int(11) DEFAULT NULL,
  `*FG_PITCH*` varchar(1) NOT NULL DEFAULT '',
  `TJ_Date` date DEFAULT NULL,
  `Fastball_RPM` int(11) DEFAULT NULL,
  `Breaking_RPM` int(11) DEFAULT NULL,
  `Command_present` int(11) DEFAULT NULL,
  `Fastball_present` int(11) DEFAULT NULL,
  `Changeup_present` int(11) DEFAULT NULL,
  `Curveball_present` int(11) DEFAULT NULL,
  `Slider_present` int(11) DEFAULT NULL,
  `Cutter_present` int(11) DEFAULT NULL,
  `Splitter_present` int(11) DEFAULT NULL,
  `Command_future` int(11) DEFAULT NULL,
  `Fastball_future` int(11) DEFAULT NULL,
  `Changeup_future` int(11) DEFAULT NULL,
  `Curveball_future` int(11) DEFAULT NULL,
  `Slider_future` int(11) DEFAULT NULL,
  `Cutter_future` int(11) DEFAULT NULL,
  `Splitter_future` int(11) DEFAULT NULL,
  `*MLB_HIT*` varchar(1) NOT NULL DEFAULT '',
  `hit` int(11) DEFAULT NULL,
  `power` int(11) DEFAULT NULL,
  `run` int(11) DEFAULT NULL,
  `arm` int(11) DEFAULT NULL,
  `field` int(11) DEFAULT NULL,
  `*MLB_PITCH*` varchar(1) NOT NULL DEFAULT '',
  `fastball` int(11) DEFAULT NULL,
  `change` int(11) DEFAULT NULL,
  `curve` int(11) DEFAULT NULL,
  `slider` int(11) DEFAULT NULL,
  `cutter` int(11) DEFAULT NULL,
  `splitter` int(11) DEFAULT NULL,
  `other` int(11) DEFAULT NULL,
  `control` int(11) DEFAULT NULL,
  `NSBL_Team` varchar(50) DEFAULT '',
  `NSBL_Salary` decimal(32,3),
  `NSBL_Year` varchar(50) DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Create syntax for TABLE '_master_prospects'
CREATE TABLE `_master_prospects` (
  `superAdj_FV` varchar(63) DEFAULT NULL,
  `adj_FV` varchar(63) DEFAULT NULL,
  `avg_FV` varchar(75) DEFAULT NULL,
  `ofp_FV` varchar(63) DEFAULT NULL,
  `*BIO*` varchar(1) NOT NULL DEFAULT '',
  `fnames` varchar(129) DEFAULT NULL,
  `lnames` varchar(129) DEFAULT NULL,
  `age` varchar(51) DEFAULT NULL,
  `position` varchar(16) DEFAULT NULL,
  `bats` varchar(8) DEFAULT NULL,
  `throws` varchar(8) DEFAULT NULL,
  `height` varchar(11) DEFAULT NULL,
  `weight` varchar(11) DEFAULT NULL,
  `p_type` varchar(12) NOT NULL DEFAULT '',
  `FV_pts` bigint(20) NOT NULL DEFAULT '0',
  `FV_weight` decimal(16,0) NOT NULL DEFAULT '0',
  `*IDs*` varchar(1) NOT NULL DEFAULT '',
  `year` int(11) NOT NULL DEFAULT '0',
  `prospect_id` int(11) unsigned NOT NULL DEFAULT '0',
  `mlb_id` int(11) NOT NULL DEFAULT '0',
  `mlb_draft_id` varchar(64) DEFAULT NULL,
  `fg_major_id` int(11) DEFAULT NULL,
  `fg_minor_id` varchar(64) DEFAULT NULL,
  `*FG*` varchar(1) NOT NULL DEFAULT '',
  `FGOvrRnk` bigint(20) DEFAULT NULL,
  `FGSchool` varchar(64) DEFAULT NULL,
  `FG_Athleticism` bigint(20) DEFAULT NULL,
  `FG_Performer` bigint(20) DEFAULT NULL,
  `FG_Risk` bigint(20) DEFAULT NULL,
  `FG_Variance` varchar(16) DEFAULT NULL,
  `FG_ETA` bigint(20) DEFAULT NULL,
  `FG_FV` bigint(20) DEFAULT NULL,
  `FG_Video` text,
  `FG_ShortBlurb` text,
  `FG_Blurb` text,
  `*mlb*` varchar(1) NOT NULL DEFAULT '',
  `MLB_School` varchar(64) DEFAULT NULL,
  `MLB_Team` varchar(32) DEFAULT NULL,
  `MLB_Drafted` varchar(32) DEFAULT NULL,
  `MLB_Signed` varchar(32) DEFAULT NULL,
  `MLB_ETA` bigint(20) DEFAULT NULL,
  `MLB_FV` bigint(20) DEFAULT NULL,
  `MLB_Blurb` text,
  `*mi*` varchar(1) NOT NULL DEFAULT '',
  `mi_team` varchar(32) DEFAULT NULL,
  `mi_teamRank` int(11) DEFAULT NULL,
  `mi_grade` varchar(16) DEFAULT NULL,
  `mi_eta` varchar(64) DEFAULT NULL,
  `mi_FV` int(11) DEFAULT NULL,
  `*FG_PRO*` varchar(1) NOT NULL DEFAULT '',
  `FG_Team` varchar(32) DEFAULT NULL,
  `FG_Level` varchar(8) DEFAULT NULL,
  `FG_OrgRank` int(11) DEFAULT NULL,
  `FG_Signed` varchar(64) DEFAULT NULL,
  `*FG_DRAFT*` varchar(1) NOT NULL DEFAULT '',
  `FG_DraftRank` int(11) DEFAULT NULL,
  `FG_DraftPick` int(11) DEFAULT NULL,
  `FG_DraftTeam` varchar(32) DEFAULT NULL,
  `*MLB_PRO*` varchar(1) NOT NULL DEFAULT '',
  `MLB_OrgRank` int(11) DEFAULT NULL,
  `MLB_OvrRank` int(11) DEFAULT NULL,
  `*MLB_DRAFT*` varchar(1) NOT NULL DEFAULT '',
  `MLB_Grade` varchar(64) DEFAULT NULL,
  `MLB_Commit` varchar(64) DEFAULT NULL,
  `*OFP*` varchar(1) NOT NULL DEFAULT '',
  `FG_Hitters_pOFP` varchar(63) DEFAULT NULL,
  `FG_Hitters_fOFP` varchar(63) DEFAULT NULL,
  `MLB_Hitters_OFP` varchar(63) DEFAULT NULL,
  `FG_Pitchers_pOFP` varchar(67) DEFAULT NULL,
  `FG_Pitchers_fOFP` varchar(67) DEFAULT NULL,
  `MLB_Pitchers_OFP` varchar(70) DEFAULT NULL,
  `*BONUS_OFP*` varchar(1) NOT NULL DEFAULT '',
  `MaxVelo_Bonus` decimal(15,4) DEFAULT NULL,
  `FastballRPM_Bonus` decimal(15,4) DEFAULT NULL,
  `BreakingRPM_Bonus` decimal(15,4) DEFAULT NULL,
  `*FG_HIT*` varchar(1) NOT NULL DEFAULT '',
  `Hit_present` int(11) DEFAULT NULL,
  `GamePower_present` int(11) DEFAULT NULL,
  `RawPower_present` int(11) DEFAULT NULL,
  `Speed_present` int(11) DEFAULT NULL,
  `Field_present` int(11) DEFAULT NULL,
  `Throws_present` int(11) DEFAULT NULL,
  `Hit_future` int(11) DEFAULT NULL,
  `GamePower_future` int(11) DEFAULT NULL,
  `RawPower_future` int(11) DEFAULT NULL,
  `Speed_future` int(11) DEFAULT NULL,
  `Field_future` int(11) DEFAULT NULL,
  `Throws_future` int(11) DEFAULT NULL,
  `*FG_PITCH*` varchar(1) NOT NULL DEFAULT '',
  `TJ_Date` date DEFAULT NULL,
  `Fastball_RPM` int(11) DEFAULT NULL,
  `Breaking_RPM` int(11) DEFAULT NULL,
  `Command_present` int(11) DEFAULT NULL,
  `Fastball_present` int(11) DEFAULT NULL,
  `Changeup_present` int(11) DEFAULT NULL,
  `Curveball_present` int(11) DEFAULT NULL,
  `Slider_present` int(11) DEFAULT NULL,
  `Cutter_present` int(11) DEFAULT NULL,
  `Splitter_present` int(11) DEFAULT NULL,
  `Command_future` int(11) DEFAULT NULL,
  `Fastball_future` int(11) DEFAULT NULL,
  `Changeup_future` int(11) DEFAULT NULL,
  `Curveball_future` int(11) DEFAULT NULL,
  `Slider_future` int(11) DEFAULT NULL,
  `Cutter_future` int(11) DEFAULT NULL,
  `Splitter_future` int(11) DEFAULT NULL,
  `*MLB_HIT*` varchar(1) NOT NULL DEFAULT '',
  `hit` int(11) DEFAULT NULL,
  `power` int(11) DEFAULT NULL,
  `run` int(11) DEFAULT NULL,
  `arm` int(11) DEFAULT NULL,
  `field` int(11) DEFAULT NULL,
  `*MLB_PITCH*` varchar(1) NOT NULL DEFAULT '',
  `fastball` int(11) DEFAULT NULL,
  `change` int(11) DEFAULT NULL,
  `curve` int(11) DEFAULT NULL,
  `slider` int(11) DEFAULT NULL,
  `cutter` int(11) DEFAULT NULL,
  `splitter` int(11) DEFAULT NULL,
  `other` int(11) DEFAULT NULL,
  `control` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'fg_grades_hitters'
CREATE TABLE `fg_grades_hitters` (
  `year` int(11) NOT NULL DEFAULT '0',
  `fg_id` varchar(64) NOT NULL DEFAULT '',
  `Hit_present` int(11) DEFAULT NULL,
  `Hit_future` int(11) DEFAULT NULL,
  `GamePower_present` int(11) DEFAULT NULL,
  `GamePower_future` int(11) DEFAULT NULL,
  `RawPower_present` int(11) DEFAULT NULL,
  `RawPower_future` int(11) DEFAULT NULL,
  `Speed_present` int(11) DEFAULT NULL,
  `Speed_future` int(11) DEFAULT NULL,
  `Field_present` int(11) DEFAULT NULL,
  `Field_future` int(11) DEFAULT NULL,
  `Throws_present` int(11) DEFAULT NULL,
  `Throws_future` int(11) DEFAULT NULL,
  PRIMARY KEY (`year`,`fg_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'fg_grades_pitchers'
CREATE TABLE `fg_grades_pitchers` (
  `year` int(11) NOT NULL DEFAULT '0',
  `fg_id` varchar(64) NOT NULL DEFAULT '',
  `TJ_Date` date DEFAULT NULL,
  `MaxVelo` int(11) DEFAULT NULL,
  `Fastball_RPM` int(11) DEFAULT NULL,
  `Breaking_RPM` int(11) DEFAULT NULL,
  `Command_present` int(11) DEFAULT NULL,
  `Command_future` int(11) DEFAULT NULL,
  `Fastball_present` int(11) DEFAULT NULL,
  `Fastball_future` int(11) DEFAULT NULL,
  `Changeup_present` int(11) DEFAULT NULL,
  `Changeup_future` int(11) DEFAULT NULL,
  `Curveball_present` int(11) DEFAULT NULL,
  `Curveball_future` int(11) DEFAULT NULL,
  `Slider_present` int(11) DEFAULT NULL,
  `Slider_future` int(11) DEFAULT NULL,
  `Cutter_present` int(11) DEFAULT NULL,
  `Cutter_future` int(11) DEFAULT NULL,
  `Splitter_present` int(11) DEFAULT NULL,
  `Splitter_future` int(11) DEFAULT NULL,
  PRIMARY KEY (`year`,`fg_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'fg_prospects_draft'
CREATE TABLE `fg_prospects_draft` (
  `year` int(11) unsigned NOT NULL,
  `prospect_id` int(11) NOT NULL DEFAULT '0',
  `fg_id` varchar(64) NOT NULL DEFAULT '',
  `full_name` varchar(64) DEFAULT '',
  `fname` varchar(32) DEFAULT '',
  `lname` varchar(32) DEFAULT '',
  `position` varchar(16) DEFAULT NULL,
  `bats` varchar(8) DEFAULT NULL,
  `throws` varchar(8) DEFAULT NULL,
  `height` int(11) DEFAULT NULL,
  `weight` int(11) DEFAULT NULL,
  `age` decimal(8,1) DEFAULT '0.0',
  `est_years` varchar(16) DEFAULT NULL,
  `school` varchar(64) DEFAULT NULL,
  `athleticism` int(11) DEFAULT NULL,
  `performer` int(11) DEFAULT NULL,
  `risk` int(11) DEFAULT NULL,
  `variance` varchar(16) DEFAULT NULL,
  `eta` int(11) DEFAULT NULL,
  `fv` int(11) DEFAULT NULL,
  `video` text,
  `short_blurb` text,
  `blurb` text,
  `college_commit` varchar(64) DEFAULT NULL,
  `draft_rank` int(11) DEFAULT NULL,
  `ovr_rank` int(11) DEFAULT '0',
  `pick_num` int(11) DEFAULT NULL,
  `pick_team` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`year`,`prospect_id`,`fg_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'fg_prospects_international'
CREATE TABLE `fg_prospects_international` (
  `year` int(11) unsigned NOT NULL,
  `prospect_id` int(11) NOT NULL DEFAULT '0',
  `fg_id` varchar(64) NOT NULL DEFAULT '',
  `full_name` varchar(64) DEFAULT '',
  `fname` varchar(32) DEFAULT '',
  `lname` varchar(32) DEFAULT '',
  `position` varchar(16) DEFAULT NULL,
  `bats` varchar(8) DEFAULT NULL,
  `throws` varchar(8) DEFAULT NULL,
  `height` int(11) DEFAULT NULL,
  `weight` int(11) DEFAULT NULL,
  `age` decimal(8,1) DEFAULT '0.0',
  `est_years` varchar(16) DEFAULT NULL,
  `school` varchar(64) DEFAULT NULL,
  `athleticism` int(11) DEFAULT NULL,
  `performer` int(11) DEFAULT NULL,
  `risk` int(11) DEFAULT NULL,
  `variance` varchar(16) DEFAULT NULL,
  `eta` int(11) DEFAULT NULL,
  `fv` int(11) DEFAULT NULL,
  `video` text,
  `short_blurb` text,
  `blurb` text,
  `int_rank` int(11) DEFAULT NULL,
  PRIMARY KEY (`year`,`prospect_id`,`fg_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'fg_prospects_professional'
CREATE TABLE `fg_prospects_professional` (
  `year` int(11) unsigned NOT NULL,
  `prospect_id` int(11) NOT NULL DEFAULT '0',
  `fg_id` varchar(64) NOT NULL DEFAULT '',
  `full_name` varchar(64) DEFAULT NULL,
  `fname` varchar(32) DEFAULT '',
  `lname` varchar(32) DEFAULT '',
  `position` varchar(16) DEFAULT NULL,
  `bats` varchar(8) DEFAULT NULL,
  `throws` varchar(8) DEFAULT NULL,
  `height` int(11) DEFAULT NULL,
  `weight` int(11) DEFAULT NULL,
  `age` decimal(8,1) DEFAULT NULL,
  `est_years` varchar(16) DEFAULT NULL,
  `school` varchar(64) DEFAULT NULL,
  `athleticism` int(11) DEFAULT NULL,
  `performer` int(11) DEFAULT NULL,
  `risk` int(11) DEFAULT NULL,
  `variance` varchar(16) DEFAULT NULL,
  `eta` int(11) DEFAULT NULL,
  `fv` int(11) DEFAULT '0',
  `video` text,
  `short_blurb` text,
  `blurb` text,
  `level` varchar(8) DEFAULT NULL,
  `org_rank` int(11) DEFAULT NULL,
  `ovr_rank` int(11) DEFAULT NULL,
  `signed` varchar(64) DEFAULT NULL,
  `team` varchar(32) DEFAULT '',
  PRIMARY KEY (`year`,`prospect_id`,`fg_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'fg_raw'
CREATE TABLE `fg_raw` (
  `prospect_type` text,
  `Age` text,
  `Agent` text,
  `Arm` text,
  `Athleticism` text,
  `Bats` text,
  `BirthDate` text,
  `CB` text,
  `CH` text,
  `CMD` text,
  `CT` text,
  `CollegeCommit` text,
  `Delivery` text,
  `Dist_Raw` text,
  `Draft` text,
  `DraftRank` text,
  `ETA_Current` text,
  `FB` text,
  `FV_Current` text,
  `FirstName` text,
  `Fld` text,
  `Frame` text,
  `Game` text,
  `Height` text,
  `Hit` text,
  `ID` text,
  `LastName` text,
  `Org_Rank` text,
  `Ovr_Rank` text,
  `Ovr_Summary` text,
  `Performer` text,
  `PlayerId` text,
  `Position` text,
  `ProjBonus` text,
  `ProjTeam` text,
  `RPM` text,
  `Range` text,
  `Raw` text,
  `Risk_Current` text,
  `RowID` text,
  `SL` text,
  `SPL` text,
  `School` text,
  `Season` text,
  `Spd` text,
  `State` text,
  `Summary` text,
  `TJDate` text,
  `TLDR` text,
  `Team` text,
  `Throws` text,
  `Touch` text,
  `Trend` text,
  `Type` text,
  `Variance` text,
  `Vel` text,
  `Weight` text,
  `YouTube` text,
  `bRPM` text,
  `cBonus` text,
  `cDraftSchool` text,
  `cETA` text,
  `cFV` text,
  `cHeight` text,
  `cORG` text,
  `cOVR` text,
  `cRank` text,
  `cRisk` text,
  `cSeason` text,
  `cWeight` text,
  `data` text,
  `fArm` text,
  `fCB` text,
  `fCH` text,
  `fCMD` text,
  `fCT` text,
  `fFB` text,
  `fFld` text,
  `fGame` text,
  `fHit` text,
  `fRPM` text,
  `fRaw` text,
  `fSL` text,
  `fSPL` text,
  `fSpd` text,
  `llevel` text,
  `minorMasterId` text,
  `mlevel` text,
  `pArm` text,
  `pCB` text,
  `pCH` text,
  `pCMD` text,
  `pCT` text,
  `pFB` text,
  `pFld` text,
  `pGame` text,
  `pHit` text,
  `pRaw` text,
  `pSL` text,
  `pSPL` text,
  `pSpd` text,
  `playerName` text
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'minorleagueball_professional'
CREATE TABLE `minorleagueball_professional` (
  `year` int(11) NOT NULL DEFAULT '0',
  `prospect_id` int(11) NOT NULL DEFAULT '0',
  `team` varchar(32) NOT NULL DEFAULT '',
  `team_rank` int(11) DEFAULT NULL,
  `full_name` varchar(64) NOT NULL DEFAULT '',
  `position` varchar(16) DEFAULT NULL,
  `age` int(11) DEFAULT NULL,
  `grade` varchar(16) DEFAULT NULL,
  `eta` varchar(64) DEFAULT NULL,
  `fname` varchar(32) NOT NULL DEFAULT '',
  `lname` varchar(32) NOT NULL DEFAULT '',
  `FV` int(11) DEFAULT NULL,
  `blurb` text,
  PRIMARY KEY (`year`,`team`,`fname`,`lname`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'mlb_grades_hitters'
CREATE TABLE `mlb_grades_hitters` (
  `year` int(11) NOT NULL DEFAULT '0',
  `mlb_id` varchar(64) NOT NULL DEFAULT '',
  `prospect_type` varchar(32) NOT NULL DEFAULT '',
  `hit` int(11) DEFAULT NULL,
  `power` int(11) DEFAULT NULL,
  `run` int(11) DEFAULT NULL,
  `arm` int(11) DEFAULT NULL,
  `field` int(11) DEFAULT NULL,
  PRIMARY KEY (`year`,`mlb_id`,`prospect_type`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'mlb_grades_pitchers'
CREATE TABLE `mlb_grades_pitchers` (
  `year` int(11) NOT NULL DEFAULT '0',
  `mlb_id` varchar(64) NOT NULL DEFAULT '',
  `prospect_type` varchar(32) NOT NULL DEFAULT '',
  `fastball` int(11) DEFAULT NULL,
  `change` int(11) DEFAULT NULL,
  `curve` int(11) DEFAULT NULL,
  `slider` int(11) DEFAULT NULL,
  `cutter` int(11) DEFAULT NULL,
  `splitter` int(11) DEFAULT NULL,
  `other` int(11) DEFAULT NULL,
  `control` int(11) DEFAULT NULL,
  PRIMARY KEY (`year`,`mlb_id`,`prospect_type`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'mlb_prospects_draft'
CREATE TABLE `mlb_prospects_draft` (
  `year` int(11) unsigned NOT NULL,
  `prospect_id` int(11) NOT NULL DEFAULT '0',
  `mlb_id` varchar(64) NOT NULL DEFAULT '',
  `rank` int(11) DEFAULT NULL,
  `fname` varchar(32) DEFAULT '',
  `lname` varchar(32) DEFAULT '',
  `birth_year` int(11) DEFAULT NULL,
  `birth_month` int(11) DEFAULT NULL,
  `birth_day` int(11) DEFAULT NULL,
  `school_city` varchar(64) DEFAULT NULL,
  `grade_country` varchar(64) DEFAULT NULL,
  `college_commit` varchar(64) DEFAULT NULL,
  `team` varchar(32) DEFAULT '',
  `position` varchar(16) DEFAULT '',
  `bats` varchar(8) DEFAULT '',
  `throws` varchar(8) DEFAULT '',
  `height` int(11) DEFAULT NULL,
  `weight` int(11) DEFAULT NULL,
  `drafted` varchar(32) DEFAULT '',
  `signed` int(11) DEFAULT NULL,
  `pre_top100` int(11) DEFAULT NULL,
  `eta` int(11) DEFAULT NULL,
  `FV` int(11) NOT NULL DEFAULT '0',
  `twitter` varchar(32) DEFAULT '',
  `blurb` text,
  PRIMARY KEY (`year`,`prospect_id`,`mlb_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'mlb_prospects_international'
CREATE TABLE `mlb_prospects_international` (
  `year` int(11) unsigned NOT NULL,
  `prospect_id` int(11) NOT NULL DEFAULT '0',
  `mlb_id` varchar(64) NOT NULL DEFAULT '',
  `rank` int(11) DEFAULT NULL,
  `fname` varchar(32) DEFAULT '',
  `lname` varchar(32) DEFAULT '',
  `birth_year` int(11) DEFAULT NULL,
  `birth_month` int(11) DEFAULT NULL,
  `birth_day` int(11) DEFAULT NULL,
  `school_city` varchar(64) DEFAULT NULL,
  `grade_country` varchar(64) DEFAULT NULL,
  `college_commit` varchar(64) DEFAULT NULL,
  `team` varchar(32) DEFAULT '',
  `position` varchar(16) DEFAULT '',
  `bats` varchar(8) DEFAULT '',
  `throws` varchar(8) DEFAULT '',
  `height` int(11) DEFAULT NULL,
  `weight` int(11) DEFAULT NULL,
  `drafted` varchar(32) DEFAULT '',
  `signed` int(11) DEFAULT NULL,
  `pre_top100` int(11) DEFAULT NULL,
  `eta` int(11) DEFAULT NULL,
  `FV` int(11) NOT NULL DEFAULT '0',
  `twitter` varchar(32) DEFAULT '',
  `blurb` text,
  PRIMARY KEY (`year`,`prospect_id`,`mlb_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'mlb_prospects_professional'
CREATE TABLE `mlb_prospects_professional` (
  `year` int(11) unsigned NOT NULL,
  `prospect_id` int(11) NOT NULL DEFAULT '0',
  `mlb_id` int(11) NOT NULL,
  `rank` int(11) DEFAULT NULL,
  `fname` varchar(32) DEFAULT NULL,
  `lname` varchar(32) DEFAULT NULL,
  `birth_year` int(11) DEFAULT NULL,
  `birth_month` int(11) DEFAULT NULL,
  `birth_day` int(11) DEFAULT NULL,
  `school_city` varchar(64) DEFAULT NULL,
  `grade_country` varchar(64) DEFAULT NULL,
  `college_commit` varchar(64) DEFAULT NULL,
  `team` varchar(32) DEFAULT '',
  `position` varchar(16) DEFAULT '',
  `bats` varchar(8) DEFAULT '',
  `throws` varchar(8) DEFAULT '',
  `height` int(11) DEFAULT NULL,
  `weight` int(11) DEFAULT NULL,
  `drafted` varchar(32) DEFAULT '',
  `signed` varchar(32) DEFAULT '',
  `pre_top100` int(11) DEFAULT NULL,
  `eta` int(11) DEFAULT NULL,
  `FV` int(11) NOT NULL DEFAULT '0',
  `twitter` varchar(32) DEFAULT '',
  `blurb` text,
  PRIMARY KEY (`year`,`prospect_id`,`mlb_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Create syntax for TABLE 'professional_prospects'
CREATE TABLE `professional_prospects` (
  `prospect_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `birth_year` int(11) DEFAULT NULL,
  `birth_month` int(11) DEFAULT NULL,
  `birth_day` int(11) DEFAULT NULL,
  `mlb_id` int(11) NOT NULL,
  `mlb_draft_id` varchar(64) DEFAULT NULL,
  `mlb_international_id` varchar(64) DEFAULT NULL,
  `fg_minor_id` varchar(64) DEFAULT NULL,
  `fg_major_id` int(11) DEFAULT NULL,
  `mlb_fname` varchar(64) DEFAULT NULL,
  `mlb_lname` varchar(64) DEFAULT NULL,
  `fg_fname` varchar(64) DEFAULT NULL,
  `fg_lname` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`prospect_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3292 DEFAULT CHARSET=latin1;
"""

db.query(q)

